spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;INIT=create schema if not exists TEST\;
  jpa:
    show-sql: true
    format-sql: true
    dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create

server:
  error:
    include-message: always
